#!/usr/bin/env bash
# Start the update. Run this on the replicated MW1.4->MW1.5 environment

#change the PWD to the directory generated by AWS-cloning scripts
cd ~/mw15_update/
# First, load the configuration variables:

source configs.replica
# read the wiki-password, database name, username from the configs.replica file and insert it to the python-source code
# UGLY :(
sed "s/^wikipassword = \"xxxxxxxx\"/wikipassword = \"$wikipassword\"/" translator.py > tempfile
mv tempfile translator.py
sed "s/^wikiusername = \"wikiuser\"/wikiusername = \"$wikiusername\"/" translator.py > tempfile
mv tempfile translator.py
sed "s/^wikidbname = \"wikidb\"/wikidbname = \"$wikidbname\"/" translator.py > tempfile
mv tempfile translator.py


# check the first line number to be grabbed from original server
first_line_number=$(wc -l $logfile |tr " " "\n"|head -1)

# start gathering log-file
((ssh -o StrictHostKeyChecking=no $aws_original_hostname "tail -f ${logfile} -n +${first_line_number}" > $local_log_cache) &)
# remember to terminate that ssh+tail process from memory

#now, do the mediawiki update
echo "DONE!"
echo "Now, run \"std_update_mwiki14-15.sh\""
echo "Please note that there is an extra bash-shell running ssh+tail transfering the query-log to the parallel universe."
echo "End that process when the upgrade is finished"