# Start the update. Run this on the replicated MW1.4->MW1.5 environment

#change the PWD to the directory generated by AWS-cloning scripts
cd ~/mw15_update/
# First, load the configuration variables:

source configs.replica
# check the first line number to be grabbed from original server
first_line_number=$(wc -l $logfile |tr " " "\n"|head -1)

# start gathering log-file
((ssh -o StrictHostKeyChecking=no $aws_original_hostname "tail -f ${logfile} -n +${first_line_number}" > $local_log_cache) &)
# remember to terminate that ssh+tail process from memory

#now, do the mediawiki update
#bash std_update_mwiki14-15.sh
